"""Predefined finishing-floor operation types (50 stations)."""

OPERATION_CHOICES = [
    ("collar_attach", "Collar Attach"),
    ("sleeve_attach", "Sleeve Attach"),
    ("side_seam", "Side Seam"),
    ("bottom_hem", "Bottom Hem"),
    ("button_hole", "Button Hole"),
    ("button_attach", "Button Attach"),
    ("label_attach", "Label Attach"),
    ("back_tack", "Back Tack"),
    ("trimming", "Trimming"),
    ("ironing", "Ironing"),
    ("inspection", "Inspection"),
    ("folding", "Folding"),
    ("shoulder_attach", "Shoulder Attach"),
    ("neck_bind", "Neck Bind"),
    ("cuff_attach", "Cuff Attach"),
    ("zipper_set", "Zipper Set"),
    ("pocket_attach", "Pocket Attach"),
    ("dart_sew", "Dart Sew"),
    ("pleat", "Pleat"),
    ("waistband", "Waistband"),
    ("bartack", "Bartack"),
    ("loop_attach", "Loop Attach"),
    ("hook_eye", "Hook & Eye"),
    ("snap_attach", "Snap Attach"),
    ("elastic_insert", "Elastic Insert"),
    ("seam_finish", "Seam Finish"),
    ("overlock", "Overlock"),
    ("coverstitch", "Coverstitch"),
    ("flatlock", "Flatlock"),
    ("chainstitch", "Chainstitch"),
    ("seam_tape", "Seam Tape"),
    ("fusing", "Fusing"),
    ("pressing", "Pressing"),
    ("spot_clean", "Spot Clean"),
    ("thread_trim", "Thread Trim"),
    ("qc_hold", "QC Hold"),
    ("repair_station", "Repair Station"),
    ("rework", "Rework"),
    ("sort_bundle", "Sort & Bundle"),
    ("load_line", "Load Line"),
    ("unload_line", "Unload Line"),
    ("pack_prep", "Pack Prep"),
    ("poly_bag", "Poly Bag"),
    ("carton", "Carton"),
    ("pallet", "Pallet"),
    ("material_feed", "Material Feed"),
    ("template_cut", "Template Cut"),
    ("marker_apply", "Marker Apply"),
    ("barcode_scan", "Barcode Scan"),
    ("final_release", "Final Release"),
]

assert len(OPERATION_CHOICES) == 50
