# Generated by Django 4.2.30 on 2026-04-19 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('floors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraDetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mismatch', models.BooleanField(default=False)),
                ('confidence', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('camera_id', models.CharField(max_length=50)),
                ('assigned_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to='floors.workstation')),
                ('detected_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_logs_detected', to='floors.workstation')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_logs', to='employees.employee')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'is_mismatch'], name='attendance__timesta_56ae9f_idx')],
            },
        ),
    ]
