# Generated by Django 4.2.30 on 2026-04-19 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0002_workstation_required_skill_level_linelayouttemplate'),
        ('employees', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationCameraState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mismatch', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('camera_id', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_states', to='employees.employee')),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='camera_state', to='floors.workstation')),
            ],
            options={
                'ordering': ['station_id'],
            },
        ),
    ]
