# Generated by Django 4.2.30 on 2026-04-19 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('floors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('face_encoding', models.JSONField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, upload_to='employees/')),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('skill_set', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['emp_id'],
            },
        ),
        migrations.CreateModel(
            name='StationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_assignments', to='employees.employee')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_assignments', to='floors.line')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='floors.workstation')),
            ],
            options={
                'ordering': ['-assigned_date', 'employee_id'],
                'indexes': [models.Index(fields=['assigned_date', 'is_active'], name='employees_s_assigne_ddb09d_idx')],
            },
        ),
    ]
