# Generated by Django 4.2.30 on 2026-06-14 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_stationassignment_layout_process'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationassignment',
            options={'ordering': ['-assigned_date', 'line_id', 'station_id']},
        ),
    ]
