# Generated by Django 4.2.30 on 2026-04-19 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_lines', models.IntegerField(default=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('daily_target', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='floors.floor')),
            ],
            options={
                'ordering': ['floor', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_number', models.IntegerField()),
                ('operation_type', models.CharField(choices=[('collar_attach', 'Collar Attach'), ('sleeve_attach', 'Sleeve Attach'), ('side_seam', 'Side Seam'), ('bottom_hem', 'Bottom Hem'), ('button_hole', 'Button Hole'), ('button_attach', 'Button Attach'), ('label_attach', 'Label Attach'), ('back_tack', 'Back Tack'), ('trimming', 'Trimming'), ('ironing', 'Ironing'), ('inspection', 'Inspection'), ('folding', 'Folding'), ('shoulder_attach', 'Shoulder Attach'), ('neck_bind', 'Neck Bind'), ('cuff_attach', 'Cuff Attach'), ('zipper_set', 'Zipper Set'), ('pocket_attach', 'Pocket Attach'), ('dart_sew', 'Dart Sew'), ('pleat', 'Pleat'), ('waistband', 'Waistband'), ('bartack', 'Bartack'), ('loop_attach', 'Loop Attach'), ('hook_eye', 'Hook & Eye'), ('snap_attach', 'Snap Attach'), ('elastic_insert', 'Elastic Insert'), ('seam_finish', 'Seam Finish'), ('overlock', 'Overlock'), ('coverstitch', 'Coverstitch'), ('flatlock', 'Flatlock'), ('chainstitch', 'Chainstitch'), ('seam_tape', 'Seam Tape'), ('fusing', 'Fusing'), ('pressing', 'Pressing'), ('spot_clean', 'Spot Clean'), ('thread_trim', 'Thread Trim'), ('qc_hold', 'QC Hold'), ('repair_station', 'Repair Station'), ('rework', 'Rework'), ('sort_bundle', 'Sort & Bundle'), ('load_line', 'Load Line'), ('unload_line', 'Unload Line'), ('pack_prep', 'Pack Prep'), ('poly_bag', 'Poly Bag'), ('carton', 'Carton'), ('pallet', 'Pallet'), ('material_feed', 'Material Feed'), ('template_cut', 'Template Cut'), ('marker_apply', 'Marker Apply'), ('barcode_scan', 'Barcode Scan'), ('final_release', 'Final Release')], max_length=50)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('machine_type', models.CharField(max_length=100)),
                ('standard_time', models.FloatField(help_text='SAM in minutes')),
                ('symbol_icon', models.CharField(blank=True, max_length=50)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='floors.line')),
            ],
            options={
                'ordering': ['line', 'station_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('quantity', models.IntegerField(default=0)),
                ('target', models.IntegerField(default=0)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_entries', to='floors.line')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_entries', to='floors.workstation')),
            ],
            options={
                'ordering': ['-date', 'hour', 'line_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='workstation',
            constraint=models.UniqueConstraint(fields=('line', 'station_number'), name='uniq_line_station_number'),
        ),
        migrations.AddConstraint(
            model_name='productionentry',
            constraint=models.UniqueConstraint(fields=('line', 'station', 'date', 'hour'), name='uniq_production_line_station_date_hour'),
        ),
        migrations.AddConstraint(
            model_name='line',
            constraint=models.UniqueConstraint(fields=('floor', 'line_number'), name='uniq_floor_line_number'),
        ),
    ]
