# Generated by Django 4.2.30 on 2026-04-19 11:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='required_skill_level',
            field=models.PositiveSmallIntegerField(default=1, help_text='Required operator skill level (1–5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='LineLayoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('stations', models.JSONField(default=list, help_text='List of station config dicts (number, operation, SAM, …)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layout_templates', to='floors.floor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
